name: Spin Up Orthanc
on:
  workflow_call:
jobs:
  run_build:
    name: Bash build script
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        version: [ '3.10' ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Check if Orthanc is running
        run: ps -eaf | grep Orthanc


      - name: Set up Orthanc
        run: |
          cd ${{ github.workspace }}
          Linux/Orthanc OrthancConfig.json
          

      - name: Check if Orthanc is running
        run: ps -eaf | grep Orthanc